version: "3.9"
services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rake db:create && rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/billinho
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped
