default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: billinho

test:
  <<: *default
  database: myapp_test
